apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  labels:
    app: flask-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
      - name: flask
        image: mdmusfikurrahmansifar/flask-hello:2025-12-03-194420
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service
  labels:
    app: flask-hello
    release: kps          # <-- REQUIRED for Prometheus Operator
spec:
  selector:
    app: flask-hello
  ports:
    - name: http            # <-- added
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP           # â† LoadBalancer not needed in kind
